CREATE USER bienestarAnimal IDENTIFIED BY tuClave
  DEFAULT TABLESPACE DataTableSpace
  TEMPORARY TABLESPACE temp
  QUOTA UNLIMITED ON DataTableSpace
  QUOTA UNLIMITED ON GEIndex;

GRANT CONNECT, RESOURCE TO bienestarAnimal;