CREATE TABLE Breed (
    id NUMBER(8) NOT NULL,
    createdBy VARCHAR2(50) NOT NULL,
    createdAt TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    modifiedBy VARCHAR2(50) NOT NULL,
    modifiedAt TIMESTAMP(6) NOT NULL,
    petTypeId NUMBER(8) NOT NULL, --FK
    name VARCHAR2(50) NOT NULL
);

ALTER TABLE Breed
    ADD CONSTRAINT breedPk PRIMARY KEY (idBreed)
    USING INDEX TABLESPACE GEIndex;

ALTER TABLE Breed
    ADD CONSTRAINT breedXPetTypeFK FOREIGN KEY (petTypeId) 
    REFERENCES PetType(idPetType);