CREATE TABLE Log (
    id NUMBER(8) NOT NULL,
    affectedTable VARCHAR2(50) NOT NULL,
    affectedSlot VARCHAR2(50) NOT NULL,
    lastValue VARCHAR2(50) NOT NULL,
    newValue VARCHAR2(50) NOT NULL,
    date DATE NOT NULL,
    operationType VARCHAR2(50) NOT NULL,
    createdBy VARCHAR2(50) NOT NULL,
    createdAt TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    modifiedBy VARCHAR2(50) NOT NULL,
    modifiedAt TIMESTAMP(6) NOT NULL,
    userId NUMBER(8) NOT NULL --FK
);

ALTER TABLE Log
    ADD CONSTRAINT logPk PRIMARY KEY (idLog)
    USING INDEX TABLESPACE GEIndex;

ALTER TABLE Log
    ADD CONSTRAINT logXUserFK FOREIGN KEY (userId) 
    REFERENCES User(idUser);