CREATE TABLE Parameter (
    id NUMBER(8) NOT NULL,
    name VARCHAR2(50) NOT NULL,
    description VARCHAR2(500) NOT NULL,
    createdBy VARCHAR2(50) NOT NULL,
    createdAt TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    modifiedBy VARCHAR2(50) NOT NULL,
    modifiedAt TIMESTAMP(6) NOT NULL,
    value VARCHAR2(50) NOT NULL
);

ALTER TABLE Parameter
    ADD CONSTRAINT parameterPk PRIMARY KEY (idParameter)
    USING INDEX TABLESPACE GEIndex;