CREATE TABLE Size (
    id NUMBER(8) NOT NULL,
    createdBy VARCHAR2(50) NOT NULL,
    createdAt TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    modifiedBy VARCHAR2(50) NOT NULL,
    modifiedAt TIMESTAMP(6) NOT NULL,
    name VARCHAR2(50) NOT NULL
);

ALTER TABLE Size
    ADD CONSTRAINT sizePk PRIMARY KEY (idSize)
    USING INDEX TABLESPACE GEIndex;