CREATE TABLE User (
    id NUMBER(8) NOT NULL, --FK
    userName VARCHAR2(50) NOT NULL,
    createdBy VARCHAR2(50) NOT NULL,
    createdAt TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    modifiedBy VARCHAR2(50) NOT NULL,
    modifiedAt TIMESTAMP(6) NOT NULL,
    password VARCHAR2(50) NOT NULL
);

ALTER TABLE User
    ADD CONSTRAINT userPk PRIMARY KEY (idUser)
    USING INDEX TABLESPACE GEIndex;

ALTER TABLE User
    ADD CONSTRAINT userXPersonFK FOREIGN KEY (idUser) 
    REFERENCES Person(idPerson);